In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.15527895, -0.3693154 ,  0.2998911 ,  0.77365136, -0.41586977,
         0.09680187,  0.1689428 , -0.28046608,  0.3507419 ,  0.48891917]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.07245705, 0.05849595, 0.1142243 , 0.18344672, 0.05583512,
        0.09323049, 0.10020476, 0.06393116, 0.12018292, 0.13799152]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.3726804

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8570 - loss: 0.4942
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9554 - loss: 0.1485
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9665 - loss: 0.1113
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9741 - loss: 0.0854
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9762 - loss: 0.0769


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9792 - loss: 0.0675


[0.06751347333192825, 0.979200005531311]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:2])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[2.7031433e-08, 2.9755627e-08, 1.7136388e-06, 9.8178971e-05,
        1.2947515e-10, 1.2434335e-06, 1.0198773e-11, 9.9989343e-01,
        5.7405515e-07, 4.7759913e-06],
       [7.6153334e-08, 4.5817982e-05, 9.9995160e-01, 2.1582787e-06,
        2.9287572e-16, 1.9316156e-08, 5.2366302e-09, 4.5676787e-13,
        2.4999380e-07, 8.5461421e-12]], dtype=float32)>